name: '🚀 release'
on:
  release:
    types: [published]

jobs:
  release:
    name: 🚀 release
    runs-on: ubuntu-latest
    steps:
      - name: 📚 checkout
        uses: actions/checkout@v4
      - name: 🟢 node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: 📦 install dependencies and build
        run: |
          corepack enable
          yarn install --immutable
          yarn prepare
      - name: 🚀 publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{secrets.NPM_AUTH_TOKEN}}
